                                              ?column?                                               
-----------------------------------------------------------------------------------------------------
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS height numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS is_insured boolean;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS insurance_amount numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS is_urgent boolean;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS urgent_fee numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS estimated_delivery_date timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS created_by uuid;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS cancelled_by uuid;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS cancelled_at timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS delivery_fees numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS total_amount numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS is_free_for_bidding boolean;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS proposed_price numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS negotiated_price numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS selected_bid_id uuid;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS parcel_id uuid NOT NULL;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS driver_id uuid NOT NULL;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS price numeric NOT NULL;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS responded_at timestamp without time zone;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS parcel_id uuid;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS amount numeric NOT NULL;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS metadata jsonb;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS completed_at timestamp without time zone;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS is_enabled boolean;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS fees_percentage numeric;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS fixed_fees numeric;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS min_amount numeric;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS max_amount numeric;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS config jsonb;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS driver_id uuid NOT NULL;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS latitude numeric NOT NULL;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS longitude numeric NOT NULL;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS accuracy numeric;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS speed numeric;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS bearing numeric;
 ALTER TABLE driver_locations ADD COLUMN IF NOT EXISTS recorded_at timestamp without time zone;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS garage_id uuid;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS is_email_verified boolean;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS is_phone_verified boolean;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login timestamp without time zone;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS vehicle_year integer;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS birth_date date;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS is_approved boolean;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_by uuid;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS approved_at timestamp without time zone;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by uuid;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active timestamp without time zone;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS is_profile_complete boolean;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS rating numeric;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS total_deliveries integer;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS completed_deliveries integer;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS cancelled_deliveries integer;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS last_active_at timestamp without time zone;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS latitude numeric;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS longitude numeric;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS drivers_count integer;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS parcels_count integer;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS revenue numeric;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS user_id uuid;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone NOT NULL;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS attempts integer;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE tokens ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE tokens ADD COLUMN IF NOT EXISTS user_id uuid;
 ALTER TABLE tokens ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone NOT NULL;
 ALTER TABLE tokens ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS parcel_id uuid;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS user_id uuid;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS metadata jsonb;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS is_used boolean;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS attempts integer;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone NOT NULL;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE user_tokens ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE user_tokens ADD COLUMN IF NOT EXISTS user_id uuid NOT NULL;
 ALTER TABLE user_tokens ADD COLUMN IF NOT EXISTS expires_at timestamp without time zone NOT NULL;
 ALTER TABLE user_tokens ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS capacity integer NOT NULL;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS garage_id uuid;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS driver_id uuid;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS is_available boolean;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE parcel_photos ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE parcel_photos ADD COLUMN IF NOT EXISTS parcel_id uuid;
 ALTER TABLE parcel_photos ADD COLUMN IF NOT EXISTS uploaded_at timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS id uuid NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS sender_id uuid;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS weight numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS departure_garage_id uuid;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS arrival_garage_id uuid;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS driver_id uuid;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS price numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS pickup_date timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS delivery_date timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS created_at timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS updated_at timestamp without time zone;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS length numeric;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS width numeric;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS code character varying NOT NULL;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS type character varying NOT NULL;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS phone character varying;
 ALTER TABLE otp_codes ADD COLUMN IF NOT EXISTS email character varying;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS message text;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS status character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS gender character varying;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS code character varying NOT NULL;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS response_message text;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo text;
 ALTER TABLE user_tokens ADD COLUMN IF NOT EXISTS refresh_token text NOT NULL;
 ALTER TABLE otps ADD COLUMN IF NOT EXISTS type character varying;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS location_lat character varying;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS name character varying NOT NULL;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS plate_number character varying NOT NULL;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS model character varying NOT NULL;
 ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS type character varying NOT NULL;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS currency character varying;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS method character varying NOT NULL;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS status character varying;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS transaction_id character varying;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS phone_number character varying;
 ALTER TABLE payments ADD COLUMN IF NOT EXISTS reference character varying;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS city character varying NOT NULL;
 ALTER TABLE parcel_photos ADD COLUMN IF NOT EXISTS url text NOT NULL;
 ALTER TABLE parcel_photos ADD COLUMN IF NOT EXISTS thumbnail_url text;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS region character varying NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS vehicle_color character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS tracking_number character varying NOT NULL;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS address text;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS sender_name character varying NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS sender_phone character varying NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS receiver_name character varying NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS receiver_phone character varying NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS receiver_email character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS description text;
 ALTER TABLE payment_methods_config ADD COLUMN IF NOT EXISTS method character varying NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS type character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS status character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS country character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS departure_garage_name character varying;
 ALTER TABLE garages ADD COLUMN IF NOT EXISTS phone character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS arrival_garage_name character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS national_id character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS driver_name character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS driver_phone character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_contact character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS payment_method character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS payment_status character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS signature_url text;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS emergency_phone character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS fcm_token text;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS status character varying NOT NULL;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS description text;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS receiver_address text;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS location character varying;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS location_lng character varying;
 ALTER TABLE tokens ADD COLUMN IF NOT EXISTS token text NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS garage_name character varying;
 ALTER TABLE tokens ADD COLUMN IF NOT EXISTS refresh_token text;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS user_name character varying;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS user_role character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS notes text;
 ALTER TABLE parcel_events ADD COLUMN IF NOT EXISTS photo_url text;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS email character varying NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS phone character varying NOT NULL;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS cancellation_reason text;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name character varying NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS role character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS sender_email character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS payment_phone_number character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS created_by_name character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS status character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS address text;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS city character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS region character varying;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS photo_urls ARRAY;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS video_urls ARRAY;
 ALTER TABLE parcels ADD COLUMN IF NOT EXISTS audio_urls ARRAY;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS vehicle_plate character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS vehicle_model character varying;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS driver_status character varying;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS driver_name character varying NOT NULL;
 ALTER TABLE bids ADD COLUMN IF NOT EXISTS driver_phone character varying NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS pin character varying;
(204 rows)

