services:
  - type: web
    name: procolis-backend
    runtime: image
    repo: https://github.com/alhDiallo2018/pro-colis
    plan: free
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080